name       : haskell-unordered-containers
version    : 0.2.9.0
release    : 4
source     :
    - https://hackage.haskell.org/package/unordered-containers-0.2.9.0/unordered-containers-0.2.9.0.tar.gz : 6730cb5c4a3e953e2c199d6425be08fd088ff0089a3e140d63226c052e318250
license    : BSD-3-Clause
component  : programming.haskell
summary    : Efficient hashing-based container types.
description: |
    Efficient hashing-based container types.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-hashable
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
