name       : haskell-unordered-containers
version    : 0.2.7.1
release    : 1
source     :
    - http://hackage.haskell.org/package/unordered-containers-0.2.7.1/unordered-containers-0.2.7.1.tar.gz : 2f9277f1d61c409775835f094c031fbb5462dd564d639f4f1357ee086fc4d702
license    : BSD-3-Clause
component  : programming
summary    : Efficient hashing-based container types.
description: |
    Efficient hashing-based container types.
builddeps  :
    - ghc
    - haskell-hashable
setup      : |
    sudo ghc-pkg recache
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 unordered-containers-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/unordered-containers-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/unordered-containers-$version/*.a
