name       : haskell-unordered-containers
version    : 0.2.11.0
release    : 5
source     :
    - https://hackage.haskell.org/package/unordered-containers-0.2.11.0/unordered-containers-0.2.11.0.tar.gz : 2b3a8c8d796f9c13aefd3a572c4b4ac0627726c037e832b8b43fd8804ec4a87c
license    : BSD-3-Clause
component  : programming.haskell
summary    : Efficient hashing-based container types.
description: |
    Efficient hashing-based container types.
builddeps  :
    - haskell-cabal-install
    - haskell-hashable-devel
rundeps    :
    - devel:
        - haskell-hashable-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
