name       : haskell-unordered-containers
version    : 0.2.7.1
release    : 2
source     :
    - http://hackage.haskell.org/package/unordered-containers-0.2.7.1/unordered-containers-0.2.7.1.tar.gz : 2f9277f1d61c409775835f094c031fbb5462dd564d639f4f1357ee086fc4d702
license    : BSD-3-Clause
component  : programming.haskell
summary    : Efficient hashing-based container types.
description: |
    Efficient hashing-based container types.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-hashable
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
